### ISSUE TITLE
Get "liga" out of "font-feature-settings" in css

### ISSUE THREAD

**Issue by jsignell** [pyviz-dev/sphinx_pyviz_theme#4]
ref: https://github.com/pyviz/nbsite/issues/120

**Comment by jbednar** [comment]
Oh, that looks easy; I see it there in main.css.  I guess it's as simple as deleting that text and rebuilding one of our sites to see if it worked?

**Comment by jsignell** [comment]
Yep. None of the sites depend on this yet, but I'd like them to start.

**Comment by jbednar** [comment]
Note that https://github.com/pyviz-dev/sphinx_pyviz_theme/blob/master/sphinx_pyviz_theme/static/css/main.css here isn't really maintainable; can we replace it with https://github.com/pyviz/pyviz/blob/master/doc/_static/site.css that's at least marginally human readable/editable?

**Comment by jsignell** [comment]
I am looking into using sphinx themes properly. Ideally we shouldn't be tweaking css at all on a per-project level. We should just be setting html_theme_options rather than doing this: https://github.com/ioam/sphinx_ioam_theme/issues/1

**Comment by jbednar** [comment]
Right.
